# Generated by Django 4.0.4 on 2022-05-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caughtFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fish', models.CharField(choices=[('BC', 'Black Crappie'), ('BG', 'Bluegill'), ('BH', 'Bullhead'), ('BT', 'Bull Trout'), ('BR', 'Brown Trout'), ('CC', 'Channel Catfish'), ('CT', 'Cutthroat Trout'), ('DV', 'Dolly Varden'), ('EB', 'Eastern Brook Trout'), ('GC', 'Grass Carp'), ('GR', 'Green Sunfish'), ('GS', 'Green Sturgeon'), ('KK', 'Kokanee'), ('LB', 'Largemouth Bass'), ('RB', 'Rock Bass'), ('RT', 'Rainbow Trout'), ('SB', 'Smallmouth Bass'), ('SH', 'Steelhead'), ('TM', 'Tiger Muskie'), ('WE', 'Walleye'), ('WS', 'White Sturgeon'), ('YP', 'Yellow Perch')], default='BC', max_length=2)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.river')),
            ],
        ),
    ]
