# Generated by Django 4.0.4 on 2022-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_caughtfish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='caughtfish',
            name='date',
            field=models.DateField(verbose_name='caught date'),
        ),
        migrations.AddField(
            model_name='river',
            name='lures',
            field=models.ManyToManyField(to='main_app.lure'),
        ),
    ]
